export const QUERY_KEY = {
  LOG_OUT: 'LOG_OUT',
  LOG_IN: 'LOG_IN',
  WHOAMI: 'WHOAMI',

  LOCATIONS: 'LOCATIONS',

  LIST_CLIENT: 'LIST_CLIENT',
  CLIENT_INFO: 'CLIENT_INFO',
  CLIENT_BILLING_INFO: 'CLIENT_BILLING_INFO',
  CLIENT_CATEGORY_WITH_CLIENT: 'CLIENT_CATEGORY_WITH_CLIENT',
  ALL_POST_BY_CLIENT: 'ALL_POST_BY_CLIENT',

  LOCATION_ID: 'LOCATION_ID',
  ALL_SHIFTS: 'ALL_SHIFTS',
  PLAN_SCHEDULE: 'PLAN_SCHEDULE',

  ASSIGNMENT_SCHEDULE_BY_CLIENT_WITH_TYPE:
    'ASSIGNMENT_SCHEDULE_BY_CLIENT_WITH_TYPE',
  EMP_SCHEDU_TALLY: 'EMP_SCHEDU_TALLY',
  MASTER_SCHEDULE: 'MASTER_SCHEDULE',
  MASTER_SCHEDULE_ADDTL: 'MASTER_SCHEDULE_ADDTL',
  EMP_SCHEDULE: 'EMP_SCHEDULE',
  EMP_SCHEDULE_ADDTL: 'EMP_SCHEDULE_ADDTL',
  ALL_POST: 'ALL_POST',
  ALL_ASSIGNMENT: 'ALL_ASSIGNMENT',

  JOB_TYPE: 'JOB_TYPE',
  TERMINAL: 'TERMINAL',
  SPLIT_ROLES: 'SPLIT_ROLES',

  LIST_CLIENT_SHEET: 'LIST_CLIENT_SHEET',
  VIEW_MAPPING: 'VIEW_MAPPING',
  LIST_GROUP: 'LIST_GROUP',
  SCHEDULE_FILTER: 'SCHEDULE_FILTER',
  MASTER_TALLY: 'MASTER_TALLY',
  SCHED_VER: 'SCHED_VER',
  MASTER_VER: 'MASTER_VER',

  TOKEN_VERIFY_USER: 'TOKEN_VERIFY_USER',

  SCHEDULE_VER_HISTORY: 'SCHEDULE_VER_HISTORY',
  MASTER_VER_HISTORY: 'MASTER_VER_HISTORY',
};
